os:
  - linux
  - osx
language: node_js
node_js:
  - "0.10.29"
  - "0.12.0"
  - "iojs-1"
  - "iojs-2"
  - "iojs-3"
notifications:
  recipients:
    - i@yanyiwu.com
  email:
    on_success: change
    on_failure: always
